# Generated by Django 5.2.7 on 2025-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('client', 'Клиент'), ('seller', 'Продавец')], default='client', max_length=20, verbose_name='роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
